### ISSUE TITLE
Individual newspaper titles are using old date templates

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#103]
We switched to new date templates based on what oregon did https://nebnewspapers.unl.edu/calendar-issues/

but these are not loading for the newspaper date browse: https://nebnewspapers.unl.edu/lccn/sn96080312/issues/

They seem to be our old templates instead, but not all the javascript is loading.

**Comment by techgique** [comment]
We're including the plugin to modify the calendar pages with a prefix, so the more deeply nested URLs we wanted the plugin to override are not being overridden and default to the old version.

Making the below change fixes it, but it does modify our URL for the calendar from `/calendar-issues/` to `/issues/`. Personally I don't think that's a problem. I think it's more confusing that the link text "Date" doesn't match the URL `/issues`. At least the header on that page fits though, "Browse All Issues"`onisite/urls.py`:

```python
#  url(r'^calendar-', include("onisite.plugins.calendar.urls")),
  url(r'', include("onisite.plugins.calendar.urls")),
```

**Comment by techgique** [comment]
Deployed on dev and production sites. Documentation updated: https://github.com/CDRH/open-oni_nebraska_theme/commit/45d035dca8d750f1a080f85858c3760104a663a3
