### ISSUE TITLE
Wiki pages are not existing

### ISSUE THREAD

**Issue by t-duan** [CDRH/open-oni_nebraska_theme#107]
On the following pages some Wiki-pages are linked, but they seem not to exist:
https://github.com/CDRH/open-oni_nebraska_theme/blob/master/docs/services/apache.md
https://github.com/CDRH/open-oni_nebraska_theme/blob/master/docs/services/mariadb.md
https://github.com/CDRH/open-oni_nebraska_theme/blob/master/docs/services/solr.md

**Comment by jduss4** [comment]
Hi @t-duan sorry for the delay in responding, for some reason I didn't notice your issue!

You are right, those links are going to our internal Nebraska documentation. However, similar but generalized documentation can be found in Open ONI:  https://github.com/open-oni/open-oni/tree/dev/docs/install/centos

Apache: https://github.com/open-oni/open-oni/blob/dev/docs/install/centos/services/apache.md
Mariadb: https://github.com/open-oni/open-oni/blob/dev/docs/install/centos/services/mariadb.md
Solr: https://github.com/open-oni/open-oni/blob/dev/docs/install/centos/services/solr.md

I hope that helps, and apologies once again for taking so long to respond.
