### ISSUE TITLE
Discuss removing breadcrumbs on top level pages

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#12]
I find the breadcrumbs redundant on top level pages, i.e.: 

![screen shot 2016-07-29 at 11 20 28 am](https://cloud.githubusercontent.com/assets/284315/17255375/9d195150-557e-11e6-80bd-bb7e8ab7992e.png)

in that "help" is already highlighted at the top. 

Either way though, we need some direction of when breadcrumbs should appear. This may spill over into core.

**Comment by jduss4** [comment]
Related https://github.com/open-oni/open-oni/issues/95

**Comment by jduss4** [comment]
I believe that in previous discussions we decided that we don't need any breadcrumbs as long as we clean up the display of the pages view so that it's clear how to get back to the issue page and title page, etc

**Comment by jduss4** [comment]
Partially resolved if https://github.com/open-oni/open-oni/pull/373 is closed
