### ISSUE TITLE
Just before we move site to open-oni, copy text changes to new templates

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#19]
Pages affected (add more as we find them)

- http://nebnewspapers.unl.edu/about/

**Comment by jduss4** [comment]
Related to #23 I believe

I'll copy everything except NDNP over for now again, because I recall Kay asking me to make some changes to one of the pages in nebnews a while ago that this repository probably doesn't have yet.

**Comment by jduss4** [comment]
For now I'm going to add the "about" page since that's what Kay asked me to change recently.  Just a quick scan of pages like "adding" lead me to believe they are outdated and hopefully are being addressed by #23

**Comment by karindalziel** [comment]
I added a new issue for this so closing this one
