### ISSUE TITLE
Change size of image on newspaper main page

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#25]
![screen shot 2018-08-16 at 11 15 59 am](https://user-images.githubusercontent.com/284315/44221009-d4372800-a145-11e8-8da1-13ad72e80718.png)

This is currently being controlled by the thumbnails setting in settings.py, but we might not want to change all the thumbnails on the site just for this page. It would be good to be able to call just the size we need from the image server.

**Comment by jduss4** [comment]
I think we will either need to change the tag to use the medium image, or we will need to make the `core.utils.image_urls` method `resize_url` available to the template tags so we can specify our own size

**Comment by jduss4** [comment]
PR to open oni will allow this task to be polished off:  https://github.com/open-oni/open-oni/pull/371

**Comment by techgique** [comment]
PR merged, so I presume changes to our theme are the next step

**Comment by techgique** [comment]
Close with #65 merge
