### ISSUE TITLE
Consider how we will load/access essays

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#26]
Currently, the essays for each paper are being stored in the database. With the container set up, accessing the database to change/update these will be more difficult. 

A few options:

- fix the essays loading script (this shipped with chronam but we don't think it is currently working)
- expose a way to the database? (probably not a good idea?)
- move essays to be pulled from views (probably not a great solution, could get unwieldy and we'd need to add logic to views?)

I don't mind the content of the essays being stored in views (they'd be easier to access and edit) but it's still probably better to use the database to figure out when to show which essay.

**Comment by jduss4** [comment]
Related to https://github.com/open-oni/open-oni/issues/344
