### ISSUE TITLE
Daily Nebraskan misdating

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#34]
(Moved from CDRH_General repo, Jess made it originally)

Janel brought it to my attention that she and Josh from SPEC found some issues where the date is incorrect in the image itself, so therefore the issue was mislabeled, potentially overwriting a correctly dated issue. She is working on gathering more information and looking for similar cases.

**Comment by jnlsmns** [comment]
Janel will check with Josh and add more information to this issue

**Comment by jduss4** [comment]
Deleted from `batch.xml`
```
<issue lccn="sn96080312" issueDate="1958-02-23" editionOrder="01">sn96080312/00000000024/1958022301/1958022301.xml</issue>
```

Deleted from `batch_1.xml`
```
<ndnp:issue lccn="sn96080312" issueDate="1958-02-23" editionOrder="1">sn96080312/00000000024/1958022301/1958022301_1.xml</ndnp:issue>
```

Copied to jdussault home directory and removed:
```
0419.jp2
0419.jpg
0419.pdf
0419.xml
0420.jp2
0420.jpg
0420.pdf
0420.xml
0421.jp2
0421.jpg
0421.pdf
0421.xml
0422.jp2
0422.jpg
0422.pdf
0422.xml
1958022301_1.xml
1958022301.xml
```

Purged and reingested and it's working!  :)
