### ISSUE TITLE
fix marc records for plattsmouth papers

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#37]
remove 338 field from plattsmouth papers - will need to resubmit to OCLC

Comments from Janel:

- that field is still populated when i look at the marc record linked in the us newspapers directory
- that is the field that tells you what kind of material the record was created from, which for lots of these newspapers is a fiction
- we say (because LC makes us) that these are print lccns and the 338 field is where that material designation is recorded, i think
- we came across this with pokrok zapadu
- we could probably suppress it for neb newspapers, especially since the plattsmouth papers are not in chronam at all
- it's what makes things like "volume" or "mircroform" show up in the title
- but, that's not happening when i look at the title list, so maybe that suppression has already been done?

**Comment by jnlsmns** [comment]
we decided the marc record display doesn't really matter; opening new issue for title display
