### ISSUE TITLE
Daily Nebraskan 06 batch: determine the size of just the tiffs

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#39]
@jduss4 will look at this and send info to @lweakly and @jnlsmns

**Comment by jduss4** [comment]
800.2 GB
Too big to use for DPN :(

**Comment by jduss4** [comment]
https://docs.google.com/spreadsheets/d/1UzZmNwql0OP8gCqVCV5UrEW2UJP1qjoL-dpqJ2PQdT8/edit#gid=0
for current list of sizes
