### ISSUE TITLE
Meet to discuss batch storage

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#40]
We need to meet to take stock of where batches are in what format and what needs to be kept. 

We also need to discuss how to maintain parity between versions. For instance Greg has made changes to a local batch (Daily Nebraskan?) which has not been replicated back tot he U drive. 

As a first step, @jnlsmns will ask Jenny about whether the tiffs that went into DPN maintained the folder structure (in which case we could reconstitute the batch) or if they are a flat structure.

**Comment by jduss4** [comment]
@jnlsmns found out from Jenny that all the files except for the PDFs and JP2s are stored in DPN, so the batch structure is good to go!

Here is a spreadsheet which keeps track of where batches are, although it doesn't take into account batches (and whether or not they have tiffs) on the "old" newspapers server at the moment except through the "live" column indicating whether they are browsable on the website.

https://docs.google.com/spreadsheets/d/1UzZmNwql0OP8gCqVCV5UrEW2UJP1qjoL-dpqJ2PQdT8/edit#gid=0

**Comment by karindalziel** [comment]
Closing this issue since we met, will be creating more
