### ISSUE TITLE
Pagination link locations

### ISSUE THREAD

**Issue by techgique** [CDRH/open-oni_nebraska_theme#44]
Most of our other sites we have pagination links above and below search results. I was testing pages and almost felt lost finding the pagination links once. They are currently only positioned above the re-filtering UI.

![oni-nebraska-pagination](https://user-images.githubusercontent.com/8347732/48862330-aa684f80-ed8b-11e8-9577-def85fc8d12a.png)

I suggest moving the highlighted area down between the form which has the "Refine Search" button and the "Results 1-20" text. Also duplicate numbered pagination links below the returned results. I'm thinking without the results count, page jumping, and view type but open to discussion on which of those should be duplicated as well or not.

This will clarify that the highlighted section isn't related to the "Refine Search" form and bring pagination closer to the results being displayed so pagination is more proximal whether one looks above or below the results.

If this applies to the default OpenONI template, please adjust there first or in addition to our theme :)

**Comment by karindalziel** [comment]
@techgique is this something we should change about the default theme too, do you think?

**Comment by techgique** [comment]
Yeah, I think it should be done that way for everyone. Seems like pretty cut and dry UX to me. "Would you like to have to scroll back up every time after looking over results before you can click to the next page?" :grin:

**Comment by techgique** [comment]
Addressed in https://github.com/open-oni/open-oni/pull/376
