### ISSUE TITLE
Center title in header

### ISSUE THREAD

**Issue by techgique** [CDRH/open-oni_nebraska_theme#45]
![homepage](https://user-images.githubusercontent.com/8347732/48863021-a0dfe700-ed8d-11e8-9840-b0bb44723f14.png)

The difference in length of the words wrapped around a symmetrical background image causes the header overall to not center with the contents of the body.

Suggest adding extra blank space within the background image file to pad the right side so it can remain centered by CSS along with text as the viewport varies in width, but allow us to shift the text to the left and visually center all of it.

**Comment by karindalziel** [comment]
This was done, so I'm not sure what's changed to break this. I feel like I've fixed this issue 3 times now :/

**Comment by karindalziel** [comment]
Oh! The title itself is not centered on purpose, because the nebraska icon IS centered. When I did this design I couldn't figure out how to line it up otherwise. I can take a look again.

**Comment by techgique** [comment]
You pointed out that my suggested change would un-center the background. I think that would be less noticeably awkward to me, but responsive design also complicates it. I _do_ think an uncentered background would be more noticeably awkward on smaller screens. I might just make swap the background image in the CSS in that case, perhaps with a smaller/lower res version for mobile :thinking:? You said you would mock things up and ask how others felt about it :+1:
