### ISSUE TITLE
Error when searching for phrase

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#48]
I tried to do a phrase search for "not found" from the advanced search page, and got this: 

http://cors1303.unl.edu/lccn/sn96080314/1897-05-14/ed-1/seq-16/#date1=01%2F01%2F1772&index=2&date2=12%2F31%2F1966&searchType=advanced&language=&sequence=0&words=found&proxdistance=5&rows=20&ortext=&proxtext=&phrasetext=not+found&andtext=&dateFilterType=yearRange&page=1

**Comment by jduss4** [comment]
okay agreed, I can't replicate this error anymore :)
