### ISSUE TITLE
Identify batches that need metadata changes and add to spreadsheet

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#51]
https://docs.google.com/spreadsheets/d/1UzZmNwql0OP8gCqVCV5UrEW2UJP1qjoL-dpqJ2PQdT8/edit?usp=drive_web&ouid=101461457265449463283

**Comment by jduss4** [comment]
I've gone through and done the ones that I know need a change, and confirmed those that definitely don't, but I left blank the majority for now.  I will review one by one soon

**Comment by jduss4** [comment]
I believe this is done, although more issues may come up in the future.  Joy!
