### ISSUE TITLE
Daily Nebraskan title essay

### ISSUE THREAD

**Issue by jnlsmns** [CDRH/open-oni_nebraska_theme#57]
The title essay for the Daily Nebraskan should also be associate with the following lccn: sn96080313.

**Comment by jduss4** [comment]
Done!  https://github.com/CDRH/open-oni_nebraska_theme/commit/98983b3147dfc09a4a900c5725b989ca118943b1#diff-7964a8daa49b5f301499d30dbca21fb8

Will be loaded up when the site goes to production, will not appear on the "old" nebnewspapers site
