### ISSUE TITLE
Cities are currently still hand coded

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#6]
Karin needs to move over @jduss4 's code that pulls cities from the database

![screen shot 2016-07-29 at 11 10 26 am](https://cloud.githubusercontent.com/assets/284315/17255047/149727f4-557d-11e6-9db3-7d70b93cf7bd.png)

**Comment by karindalziel** [comment]
This should be fixed with Oregon's changes to open-oni

**Comment by jduss4** [comment]
Agreed, this is now dynamic
