### ISSUE TITLE
Alphebetize cities on City/Map page

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#75]
Right now they are in some unknown order https://nebnewspapers-dev.unl.edu/newspapers/

**Comment by jduss4** [comment]
Possibly the wrong link?  On the newspapers page they are alphabetized by title
https://nebnewspapers-dev.unl.edu/map

You're right, they're looking random there.  Is that related to flex?  They are alphabetized on the old site and I don't believe that I altered the JSON defining them?
