### ISSUE TITLE
City page CSS

### ISSUE THREAD

**Issue by karindalziel** [CDRH/open-oni_nebraska_theme#9]
Karin needs to write some CSS to prettify @jduss4 's location plugin. 

She'll need a batch with more titles and places first. This would perhaps be something best to do on the live server. 

Possibly move some sample CSS back into Core?

![screen shot 2016-07-29 at 11 15 52 am](https://cloud.githubusercontent.com/assets/284315/17255189/d6d98fdc-557d-11e6-8fd2-5510cc81f939.png)

**Comment by jduss4** [comment]
I would probably recommend putting the CSS in the map plugin so that other people can benefit from it?  Unless if it's going to be fairly nebraska specific

**Comment by karindalziel** [comment]
@jduss4 yeah, I'm thinking I'll put some of it in the plugin (not core as I said above) and have probably a few overwritten styles for our theme.
