### ISSUE TITLE
used microfilm LCCN for The Conservative

### ISSUE THREAD

**Issue by jnlsmns** [CDRH/open-oni_nebraska_theme#93]
When we digitized The Conservative, we used the LCCN for a microfilm record: https://chroniclingamerica.loc.gov/lccn/sn96080161/. However, a print record exists for this title in the U.S. Newspapers Directory: https://chroniclingamerica.loc.gov/lccn/02027093/. Since the Library of Congress accepted the batch with the microfilm LCCN, I do not think we need to change it.

**Comment by techgique** [comment]
The issue on the OpenONI side is the MARC record is missing the place information, right? Can we at least get that information updated at LoC so we won't have to remember to fix that manually after future batch ingests?

**Comment by jnlsmns** [comment]
@techgique I apologize for the late response, I did not see your response to this issue until yesterday. Ideally, yes, we would be able to fix the MARC record, but the LCCN sn96080161 was cancelled at some point from the OCLC system. Laura and I are going to be meeting with Kay on Monday afternoon. We plan to discuss this issue and what steps we can take to fix the problem. In any case, I think we will have to work with the Library of Congress to get everything sorted out.

**Comment by techgique** [comment]
No problem. The fix is documented so there's no emergency. Just assume it's better to have the more "official" metadata corrected :) Hope your meeting goes well!

**Comment by techgique** [comment]
The MARC record at LoC appears to have the correct location information now, so I believe this issue can be closed.

The Conservative: https://chroniclingamerica.loc.gov/lccn/sn96080161/
MARC: https://chroniclingamerica.loc.gov/lccn/sn96080161/marc/
