### ISSUE TITLE
remove titles from other states in list of titles by location

### ISSUE THREAD

**Issue by jnlsmns** [CDRH/open-oni_nebraska_theme#97]
On the "[City](https://nebnewspapers.unl.edu/map)" page, two titles from other states are listed and should be removed: Der Nordstern, listed under Saint Cloud and Evening star, listed under Washington. 
![city](https://user-images.githubusercontent.com/38263772/54953575-9178d200-4f16-11e9-9504-3a00e6a01cbc.JPG)

**Comment by techgique** [comment]
I bet this can be resolved by applying the same filter I added to the code that provides the list of cities for the search in the header. Thanks for documenting this @jnlsmns!

**Comment by techgique** [comment]
Fixed with https://github.com/open-oni/plugin_map/commit/af34254c055c6eb04cde981981c2b358b5442da1
