### ISSUE TITLE
add cities to map

### ISSUE THREAD

**Issue by jnlsmns** [CDRH/open-oni_nebraska_theme#98]
Two cities for which we have already digitized content have not yet been plotted on the [map](https://nebnewspapers.unl.edu/map): Hemingford and Harrison. 

For the 2018 cycle we will be expanding our geographic coverage to include the following communities: 

- Loup City
- Grand Island
- O'Neill / O'Neill City
- St. Paul / Dannebrog
- Blair

**Comment by techgique** [comment]
@jduss4 Is this pretty easy to add by copy-pasting JSON and tweaking a couple strings?

**Comment by jduss4** [comment]
@techgique yes, we'd just need to look up latitude / longitude for the new places and stick them in the JSON with the newspaper title links

**Comment by jduss4** [comment]
Hemingford: 42.3216° N, 103.0730° W
- Hemingford Herald sn94055309
Harrison:  42.6872° N, 103.8827° W
- Harrison Press-Journal 2018270202
- The Journal (2018270200)
- The Sioux County Journal (2018270201)

@techgique I'll get started on adding the ones we're missing right now

Loup City: 41.2756° N, 98.9668° W
GI:  40.9264° N, 98.3420° W
O'Neill:  42.4577° N, 98.6479° W
Dannebrog: 41.1183° N, 98.5459° W
Blair:  41.5447° N, 96.1351° W

**Comment by jduss4** [comment]
I believe we still need to add the remaining places, after confirming that they have titles at this point

**Comment by apeders** [comment]
I updated the JSON file to include the missing cities as mentioned by Jessica on March 27, 2019.
